### ISSUE TITLE
i expect a playable game

### ISSUE THREAD

**Issue by besstiolle** [alechapelain/bomberman#1]
hey @alechapelain,  me sad
![](https://media2.giphy.com/media/a9xhxAxaqOfQs/giphy.gif)

me suggest : 
- [x] start working

plize

sank u

**Comment by SoulMyke77** [comment]
![image](https://media.giphy.com/media/k61nOBRRBMxva/giphy.gif)

**Comment by alechapelain** [comment]
done
fixed

<3
