### ISSUE TITLE
Not playable at all

### ISSUE THREAD

**Issue by SoulMyke77** [alechapelain/bomberman#2]
Be better in programing plz
![image](https://media1.giphy.com/media/UqZ4imFIoljlr5O2sM/giphy.gif?cid=790b7611e4d8f4c1c1075021dc98ee32997987544b3d15ac&rid=giphy.gif)

**Comment by alechapelain** [comment]
leavemealoneplz t_t

**Comment by besstiolle** [comment]
ZomG seau trou !
